spring:
  application:
    name: GATEWAY-SERVICE
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testzuul
  cloud:
    gateway:
      routes:
        - id: customer-registration-client
          uri: lb://CUSTOMER-REGISTRATION-CLIENT
          predicates:
            - Path=/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer-registration-client
                fallbackuri: forward:/customerFallBack
        - id: incident-registration-client
          uri: lb://INCIDENT-REGISTRATION-CLIENT
          predicates:
            - Path=/incidents/**
          filters:
            - name: CircuitBreaker
              args:
                name: incident-registration-client
                fallbackuri: forward:/incidentFallback

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000